sudo: required

node_js:
    - "11.10.1"

services:
    - docker

before_install:
    - docker build -t jcastrocastro/docker-react -f Dockerfile.dev .

script:
    - docker run jcastrocastro/docker-react npm run test -- --coverage
